# Generated by Django 2.2 on 2020-02-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
