# Generated by Django 2.2 on 2020-02-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_library_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='date',
        ),
    ]
