# Generated by Django 2.2 on 2020-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_library_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='date',
            field=models.DateTimeField(default=True),
        ),
    ]
