# Generated by Django 2.2 on 2020-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200210_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='date',
        ),
        migrations.AddField(
            model_name='library',
            name='pub_date',
            field=models.DateTimeField(default=1, verbose_name='date'),
            preserve_default=False,
        ),
    ]
