# Generated by Django 2.2 on 2020-02-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200210_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='pub_date',
            new_name='date',
        ),
    ]
