# Generated by Django 2.2 on 2020-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200210_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='date',
            field=models.DateTimeField(default=True),
        ),
    ]
