# Generated by Django 2.2 on 2020-02-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200210_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='date',
        ),
    ]
