# Generated by Django 2.2 on 2020-02-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200213_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='date',
            field=models.DateTimeField(verbose_name=' date published'),
        ),
    ]
