# Generated by Django 2.2 on 2020-02-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200213_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='date',
        ),
    ]
