# Generated by Django 2.2 on 2020-02-13 03:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_library_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 13, 3, 35, 35, 84104, tzinfo=utc), verbose_name=' date_published'),
            preserve_default=False,
        ),
    ]
